version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_tracker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#  app:
#    build: .
#    command: node dist/main
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - "5000:5000"  # Проверьте, на каком порту работает ваше приложение
#    depends_on:
#      - db
#    environment:
#      DATABASE_URL: postgresql://postgres:postgres@db:5432/books_tracker?schema=public

volumes:
  postgres-data:
